pipeline {
    agent any
    tools {
        git 'Git'  // Use the configured Git tool name
    }
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'master', url: 'https://github.com/mdchaus/simple-java-maven-app.git'
            }
        }
    }
}
